library(gridlayout)
library(leaflet)
library(shiny)
library(plotly)
library(gridlayout)
library(bslib)
library(shinyWidgets)
library(tidyverse)
library(shinyalert)
library(data.table)
library(rentrez)

source(file = "src/datareader.R")
source(file = "src/create_mini_cards.R")